
# apiVersion: v1
# kind: Service
# metadata:
#   name: lb-service
#   labels:
#     app: lb-service
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#   selector:
#     app: frontend-nginxapp

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend-nginxapp
#   labels: 
#     app: frontend-nginxapp
#     tier: frontend
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: frontend-nginxapp
#   template: 
#     metadata:
#       labels:
#         app: frontend-nginxapp
#         tier: frontend
#     spec:
#       containers:
#         - name: frontend-nginxapp
#           image: viswamy/myrestapi:v1
#           ports:
#             - containerPort: 8080
            

apiVersion: v1
kind: Service
metadata:
  name: studentapp-rest-api
  labels:
    app: studentapp-rest-api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: studentapp-rest-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentapp-rest-api
  labels: 
    app: studentapp-rest-api
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: studentapp-rest-api
  template: 
    metadata:
      labels:
        app: studentapp-rest-api
        tier: frontend
    spec:
      containers:
        - name: studentapp-rest-api
          image: viswamy/studentapp-restapi-docker:latest
          ports:
            - containerPort: 8080

            
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-role
  namespace: dafault
rules:
- apiGroups: [“”]
  resources: [“pods”]
  verbs: [“create”,”delete”,”get”,”list”,”patch”,”update”,”watch”]
- apiGroups: [“”]
  resources: [“pods/exec”]
  verbs: [“create”,”delete”,”get”,”list”,”patch”,”update”,”watch”]
- apiGroups: [“”]
  resources: [“pods/log”]
  verbs: [“get”,”list”,”watch”]
- apiGroups: [“”]
  resources: [“secrets”]
  verbs: [“get”]
  
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: jenkins-account
 namespace: default
 annotations:
  eks.amazonaws.com/role-arn: arn:aws:iam::491655376147:user/viswamy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-role
subjects:
- kind: ServiceAccount
  name: jenkins-account
  namespace: default
